# Generated by Django 5.2 on 2025-05-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0003_streamingplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist_app.streamingplatform",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
